//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aCROPOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDRole { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IDHousingStock { get; set; }
    
        public virtual HousingStock HousingStock { get; set; }
        public virtual Role Role { get; set; }
    }
}
