//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aCROPOL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class akropolkuryaeva21Entities : DbContext
    {
        public akropolkuryaeva21Entities()
            : base("name=akropolkuryaeva21Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bathrooms> Bathrooms { get; set; }
        public virtual DbSet<HousingStock> HousingStock { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<RentalBuildings> RentalBuildings { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
